# 服务器相关配置（SpringBoot 内置的 Web 容器 Tomcat）
# 假设在生产环境下端口号是 8888，Application Context Path 是 /tp
server:
  # 监听的端口，默认是 8080
  port: 8888
  # Application Context Path，默认是 /，注意前面的 / 不能少，这个应用上下文就是 Tomcat 用来查找对应的项目的
  servlet:
    context-path: "/hmd"

spring:
  # MySQL 数据源相关配置（数据库连接池、连接、数据库）
  # com.mysql.cj.jdbc.Driver：MySQL 数据库驱动库的类名
  # jdbc:mysql://：MySQL 的固定写法
  # 8.136.43.114、3306：域名和端口号
  # db_mysql：数据库的名称
  # serverTimezone=UTC：告诉数据库驱动 MySQL 已经把默认时区设置为了 0 时区
  # root、MySQLRoot666!：数据库的用户名和密码
  # initialSize、maxActive：初始化创建几条连接、最大连接数
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.136.43.114:3306/test_db?serverTimezone=UTC
    username: root
    password: MySQLRoot666!
    druid:
      initial-size: 5
      max-active: 10
  # MongoDB 数据源相关配置
  # mongodb://：MongoDB 的固定写法
  # root、MongoDB666!：数据库的用户名和密码
  # 8.136.43.114、27017：域名和端口号
  # test_db：数据库名
  # admin：认证用户是在哪个数据库里创建的
  # minPoolSize、maxPoolSize：连接池的最小连接数和最大连接数
  data:
    mongodb:
      uri: mongodb://root:MongoDB666!@8.136.43.114:27017/test_db?authSource=admin&minPoolSize=5&maxPoolSize=10

# 跨域处理配置，静态资源服务器的源白名单（cors 是我们自定义的属性绑定）
cors:
  allowed-origins:
    - http://8.136.43.114:5500
    - http://8.136.43.114:8888