spring:
  profiles:
    # 通过子配置文件名来"引入、激活"子配置文件，这里是个数组
    active:
      - dev # 开发环境用 dev，生产环境用 prd
  mvc:
    servlet:
      # DispatcherServlet 的加载时机：默认是 -1（延迟加载，第一次请求接口时才初始化）
      # 设置为 >=0 表示在项目启动时就初始化 DispatcherServlet，数字越小优先级越高
      load-on-startup: 0

# MyBatis-Plus 相关配置（MyBatis 的配置转交给 MyBatis-Plus 了）
myBatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.ineyee.pojo
  # 单表 CRUD 一般用 MyBatis-Plus 提供的 SQL 实现就足够了，所以这个暂时就不需要了
  # 多表查询才有自定义 SQL 的必要，打开这个，去自定义 mapper.xml 实现，跟 MyBatis-Plus 一起使用不会冲突
#  mapper-locations: classpath:mappers/*.xml

# PageHelper 相关配置
pagehelper:
  # reasonable 设置为 true，代表使分页查询合理化：
  #      当 pageNum <= 0 时，自动返回第一页的数据
  #      当 pageNum > totalPage 时，自动返回最后一页的数据
  reasonable: true