spring:
  profiles:
    # 通过子配置文件名来"引入、激活"子配置文件，这里是个数组
    active:
      - dev # 开发环境用 dev，生产环境用 prd
  mvc:
    servlet:
      # DispatcherServlet 的加载时机：默认是 -1（延迟加载，第一次请求接口时才初始化）
      # 设置为 >=0 表示在项目启动时就初始化 DispatcherServlet，数字越小优先级越高
      load-on-startup: 0